### ISSUE TITLE
Incompatibility with other editor commands

### ISSUE THREAD

**Issue by SQUASHD** [wipdev-tech/gopen#1]
Currently gopen works with terminal based editors by changing to the directory and opening a blank buffer. It would be nice to have a configurable setting to either open the editor in the netrw buffer or pass in other editor commands, like 'rider' or 'goland' etc which require the path as part of the argument to open the project. Having the option to configure the cmd execution to take in the target path as an argument would, A); allow the use of other editors, and B); allow one to open projects in nvim in netrw.

**Comment by wipdev-tech** [comment]
> Having the option to configure the cmd execution to take in the target path as an argument

Totally agree on that part. However, you got me thinking about something. You could be using rider for one project and nvim for another. This means that it might be more favorable to make the editor command configured per alias instead of a single global one... 🤔

**Comment by SQUASHD** [comment]
Could have a default behaviour that could be toggleable, then also perhaps flag to overwrite it. I think having a editor for each alias could be nice, but trying to change the behaviour for each editor could be a lot of overhead

**Comment by wipdev-tech** [comment]
Good point. That might be a good lead for me to start something.
