### ISSUE TITLE
Allow Relative Paths When Setting Aliases

### ISSUE THREAD

**Issue by SQUASHD** [wipdev-tech/gopen#5]
### Description:
Currently, the CLI requires absolute paths when setting an alias. This can be inconvenient for users who want to set an alias within their current working directory or relative to it.

### Suggestion:
It would enhance the user experience if you could set aliases using "." to represent the current working directory, or by using relative paths. This change would make the tool more flexible and user-friendly.

### Example:
Instead of having to set an alias like this:
`gopen a myproject /Users/name/projects/myproject`
You could
`gopen a myproject ./myproject`
or even just:
`gopen a myproject  .`

Thoughts?

**Comment by wipdev-tech** [comment]
When I wrote the tool, the purpose was to be able to open the project from _anywhere_ without having to worry about my current working directory. So, that means that aliases must be stored by an absolute path. I don't think aliases to relative paths are necessary because it means the user did (or has to do) a `cd` which defeats the purpose.

**Comment by SQUASHD** [comment]
I think maybe I wasn't clear in what the problem point is. If I am in a directory or terminal I'd like to write `gopen a new-project` and writing the path. If Im in a folder that I've been working on, it'd be nice to set '.' and then the absolute path is saved in the config. or if I start tabbing towards it. If I'm in my home directory and typen `gopen a portfolio repos/squashd` which is my portfolio project, it gets saved as portfolio: repos/squashd. Alternately, I've set up a project, started working on it, I'd like to `gopen a new-project .` and then it would get the absolute path to the cwd.

**Comment by wipdev-tech** [comment]
My bad... I didn't realize that it doesn't convert the relative paths to absolute ones. In that case, you're absolutely right. That would need to be fixed.
